#!/bin/bash

xhost +local:val
docker run --rm --gpus all \
   -e XAUTHORITY \
   -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
   -e="QT_X11_NO_MITSHM=1" --network=host \
   -ti vladimirivan/ihmc-valkyrie-simulator-scs-nvidia:stable /bin/bash 
xhost -local:val